GLOBAL_WINDOW_POSITION = "+300+200"
PROPORTIONAL_FONT_FAMILY = ("MS", "Sans", "Serif")

PROPORTIONAL_FONT_SIZE = 10
TEXT_ENTRY_FONT_SIZE = 12  # a little larger makes it easier to see

PROP_FONT_LINE_LENGTH = 62
FIXW_FONT_LINE_LENGTH = 80

DEFAULT_PADDING = 2
REGULAR_FONT_WIDTH = 13
FIXED_FONT_WIDTH = 7
