language: python
python:
#  - "2.7"  # killed it to simplify a lot of things ... hopefully everyone is on Py3.x now
  - "3.4"
  - "3.5"
  - "3.6"
#  - "3.7"  # TravisCI blows up with some bizarre requirements issue when attempting to do test-requirements for Py 3.7
  - "3.8"
  - "nightly"

services:
  - xvfb

# command to run tests
script: pytest

install: pip install -r requirements_for_tests.txt