

class BoxController(object):

    def __init__(self, model, view):
        """
        :param object model: holds the data of this call
        :param function callback: if set, this function will be called when any button is pressed.
        """
        self.model = model
        self.view = view


    # Methods executing when a key is pressed -------------------------------
    # If cancel, x, or escape, close ui and return None
    def x_pressed(self):
        self.nothing_selected_and_stop()

    def escape_pressed(self, event):
        self.nothing_selected_and_stop()

    def button_pressed(self, choice):
        # If cancel
        if choice.is_cancel:
            self.nothing_selected_and_stop()
        else:
            # So there has been a choice selected
            self.model.choices.selected_choice = choice
            self.model.check_callback_updated()

    def hotkey_pressed(self, keysym, keychar):
        """
        Handle an event that is generated by a person interacting with a button.  It may be a button press
        or a key press.

        TODO: Enhancement: Allow hotkey to be specified in filename of image as a shortcut too!!!
        """
        if keysym != keychar:  # A special character
            hotkey_pressed = '<{}>'.format(keysym)
        else:
            hotkey_pressed = keysym

        sucess = self.model.choices.select_choice_from_hotkey(hotkey_pressed)

        if sucess:
            self.model.check_callback_updated()
        else:
            print("Event not understood")



    def image_pressed(self, filename, row, column):
        self.model.choices.select_choice_from_text(None)
        self.model.row_column_selected = (row, column)
        self.model.model_updated()

    def nothing_selected_and_stop(self):
        self.model.choices.select_choice_from_text(None)
        self.model.row_column_selected = None
        self.model.stop = True
        self.model.model_updated()

